### ISSUE TITLE
Do you think there will be an increase or decrease in website visits from game consoles?

### ISSUE THREAD

**Issue by kingkool68** [maban/ama#4]

**Comment by maban** [comment]
[Remy tweeted a couple of days ago](https://twitter.com/rem/status/712921911672639488) the stats for jsbin which saw 373 visits last month from an Xbox. As the browsers in consoles get better, I think more people will end up using them (consciously or subconsciously – such as if a link takes them to the browser as opposed to launching the browser).

If [trends continue](https://speakerdeck.com/anna/what-we-can-learn-from-game-console-browsers-1?slide=11), it will increase, but console units themselves are losing ground to the tablet and smartphone market. So I think that website visits will increase, but only if the console market can continue to exist.
